language: node_js
node_js: 
  - "lts/*"

cache:
  npm: true
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

install:
  - npm ci

script:
  - npm run ci